name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        php: ["8.0.27", "8.1.14", "8.2.1"]

    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: pmmp/setup-php-action@7e0f5f0a95e9d45d1d5fab0e1ee7555fa3b04339
        with:
          php-version: ${{ matrix.php }}
          install-path: ${{ github.workspace}}/php

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress
